version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto20
    commands:
      - echo Installing dependencies
      - chmod +x ./gradlew
  pre_build:
    commands:
      - echo Running pre-build actions
      - ./gradlew --version
      - ./gradlew clean test --no-daemon
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew assemble --no-daemon
  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Listing Build artifacts:"
      - find build/libs -name "*.jar"
      - echo Uploading build artifacts to S3
      - aws s3 cp build/libs/*.jar s3://skodaappdevl/Skoda_BuildArtifacts/ --region eu-central-1  # Upload to S3 bucket

artifacts:
  files:
    - '**/*.jar'
  discard-paths: yes

cache:
  paths:
    - ~/.gradle/wrapper/
    - ~/.gradle/caches/



