version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto20  # Since you're using Java 20
    commands:
      - echo Installing dependencies
      - ./gradlew --no-daemon clean build  # Runs Gradle build
  pre_build:
    commands:
      - echo Running pre-build actions
      - ./gradlew --no-daemon test  # Running tests
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew --no-daemon assemble  # Assembling the application
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading build artifacts to S3
      - aws s3 cp build/libs/*.jar s3://skodaappdevl/Skoda_BuildArtifacts/ --region eu-central-1  # Upload to S3 bucket
artifacts:
  files:
    - build/libs/*.jar  # Collect the JAR file(s)
  discard-paths: yes

cache:
  paths:
    - ~/.gradle/wrapper/
    - ~/.gradle/caches/
