version: 0.2

env:
  secrets-manager:
    DB_HOST: skoda_dbsecret:DB_HOST
    DB_PORT: skoda_dbsecret:DB_PORT
    DB_NAME: skoda_dbsecret:DB_NAME
    DB_USER: skoda_dbsecret:DB_USER
    DB_PASSWORD: skoda_dbsecret:DB_PASSWORD

phases:
  install:
    runtime-versions:
      java: corretto20
    commands:
      - echo Installing dependencies
      - chmod +x ./gradlew
  pre_build:
    commands:
      - echo Running pre-build actions
      - ./gradlew --version
      - ./gradlew clean test --no-daemon
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew assemble --no-daemon
  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Listing Build artifacts:"
      - ls -l app/build/libs
      - echo Uploading build artifacts to S3
      - aws s3 cp app/build/libs/app.jar s3://skodaappdevl/Skoda_BuildArtifacts/ --region eu-central-1

artifacts:
  discard-paths: no
  files:
    - app/build/libs/app.jar
    - scripts/*
    - appspec.yml

cache:
  paths:
    - ~/.gradle/wrapper/
    - ~/.gradle/caches/
